name: pyuvdata-test
channels:
  - conda-forge
dependencies:
  - numpy
  - scipy
  - astropy
  - h5py
  - matplotlib
  - python-casacore # Want to be able to read/write MS files.
  - pip:
    - git+https://github.com/RadioAstronomySoftwareGroup/pyuvdata.git@refs/pull/995/head
    #- git+https://github.com/RadioAstronomySoftwareGroup/pyuvdata#egg=pyuvdata
